artifacts_root: artifacts


# ------------------------------------------ Data_Ingestion ------------------------------------ 


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/SubramanyaNayak-github/Datasets/raw/main/Consignment_pricing_raw.csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
